apiversion: v1
kind: PersistentVolumeClaim
metadata:
  name: ebs-dynamic
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: roboshop-ebs
  resources:
    requests:
      storage: 10Gi
---
apiVersion: v1
kind: Pod
metadata:
 name: nginx
 labels:
   purpose: ebs-dynamic
spec:
  containers:
  - name: nginx
    image: nginx
    volumeMounts:
    - name: nginx-html
      mountPath: /usr/share/nginx/html
  # nodeSelector:
  #   topology.kubernetes.io/zone: us-east-1a  # don't need nodeselector as disk won't create first, after pod is scheduled on a node then disk is created on that node
  volumes:
  - name: nginx-html
    persistentVolumeClaim:
       claimName: ebs-dynamic
---
apiVersion: v1
kind: Pod
metadata: 
   name: nginx-ebs-dynamic
spec:
  type: LoadBalancer
  selector: 
    purpose: ebs-dynamic
  ports:
  - protocal: TCP
    port: 80
    targetPort: 80
    nodePort: 30007

