# creating pv is k8 admin job
apiVersion: v1
kind: PersistentVolume
metadata:
  name: ebs-ststic
spec:
  accessModes:
  - ReadWriteOnce
  PersistentVolumeReclaimPolicy: Retain  # means don't delete data #recycle delete data not the disk
  capacity:
    storage: 10Gi
  csi:
    driver: ebs.csi.aws.com
    fsType: ext4
    volumeHandle: vol-0e896783cf49d4009