apiversion: v1
kind: PersistentVolume
metadata:
  name: efs-static
spec:
  capacity:
    storage: 10Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  storageClassName: ""  #should be empty on static
  persistentVolumeReclaimPolicy: Retain
  csi:
    driver: efs.csi.aws.com
    volumehandle: 

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: efs-static
spec:
  accessModes:
  - ReadWriteMany
  storageClassName: ""
  resources:
    requests:
      storage: 10Gi

---
apiVersion: v1
kind: Pod
metadata:
 name: nginx
 labels:
   purpose: efs-static
spec:
  containers:
  - name: nginx
    image: nginx
    volumeMounts:
    - name: nginx-html
      mountPath: /usr/share/nginx/html
  nodeSelector:
    topology.kubernetes.io/zone: us-east-1a
  volumes:
  - name: nginx-html
    persistentVolumeClaim:
       claimName: efs-static
---
apiVersion: v1
kind: Pod
metadata: 
   name: efs-static
spec:
  type: LoadBalancer
  selector: 
    purpose: efs-static
  ports:
  - protocal: TCP
    port: 80
    targetPort: 80
    nodePort: 30007
