apiVersion: v1
kind: Pod
metadata:
  name: roboshop
  namespace: roboshop
  labels:
    project: roboshop
    environment: dev
spec:
  containers:
  - name: nginx
    image: nginx
    Ports:
    - containerPort: 80 
    