apiVersion: v1
kind: Pod
metadata:
  name: resource-limits
spec:
  containers:
  - name: nginx
    image: nginx
    resource:
      requests:
       cpu: "250m"
       memory: "50mi"
      limits:
       cpu: "500m"
       memory: "100mi"
