apiVersion: apps/v1
kind: Deployment
metadata:
   name: nginx
   labels:
     purpose: deployment-demo
     environment: dev
spec:
  replicas: 1
  selector:
    matchLabels:
      purpose: deployment-demo
      environment: dev
  template:
    metadata:
     labels:
       purpose: deployment-demo
       environment: dev
    spec:
      nodeSelector: 
        kubernetes.io/hostname: ip-192-168-54-183.ec2.internal   
      containers:
      - name: nginx
        image: nginx:latest
      tolerations:
      - key: "env"
        operator: "Equal"
        value: "dev"
        effect: "NoSchedule"
---
apiVersion: v1
kind: Service
metadata:
  name: nginx
spec:
  selector:
    purpose: deployment-demo
    environment: dev
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
