apiVersion: v1
kind: Pod
metadata:
 name: nginx
spec:
  affinity:
    nodeAffinity:
    #hard rule
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:  # AND
          - key: topology.kubernetes.io/zone
            operator: In
            values:
            - us-east-1b
        #- matchExpressions:  OR      matchExpressions inside ONE nodeSelectorTerm → AND  &  Multiple nodeSelectorTerms → OR
          - key: disktype
            operator: In
            values:
            - ssd
            #soft rule
      preferredDuringSchedulingIgnoredDuringExecution:
      - weight: 1
        preference:
          matchExpressions:
          - key: project
            operator: In
            values:
            - roboshop
      - weight: 20
        preference:
          matchExpressions:
          - key: project
            operator: In
            values:
            - amazon
  containers:
  - name: nginx
    image: nginx
    imagePullPolicy: Always
